- .github/workflows/test-contracts.yml
- slither.config.json
- src/CreateX.sol
This PR finetunes the Slither configuration file `slither.config.json` in a way that it excludes the detectors that are false positives for `CreateX` (for comparison see the warnings [here](https://github.com/pcaversaccio/createx/actions/runs/6637814580/job/18032879712#step:15:269)). Furthermore, I add an additional step in the CI that uploads the SARIF file. Note that `fail_on: none` is required to let the SARIF upload step run if Slither finds issues.
> 🔒 Finetune Slither Configurations

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
- pnpm-lock.yaml
This PR changes the Base Sepolia block explorer link(s) to the recently launched Etherscan instance [`sepolia.basescan.org`](https://sepolia.basescan.org). Furthermore, I also bump `ethers` to the latest version [`6.9.2`](https://github.com/ethers-io/ethers.js/releases/tag/v6.9.2).
> ♻️ Update Base Sepolia Explorer Link and Bump `ethers` to Version `6.9.2`

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add OP-Endurance test network deployment: [`0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed`](https://explorer-l2-testnet.fusionist.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed). Closes #74.
> ➕ Add OP-Endurance Test Network Deployment

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
- pnpm-lock.yaml
Add Blast test network deployment: [`0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed`](https://testnet.blastscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed). Closes #82.
> ➕ Add Blast Test Network Deployment

- test/internal/CreateX._efficientHash.t.sol
- test/invariants/CreateX_Invariants.t.sol
Due to the `forge-std` release [`v1.8.0`](https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0) that, amongst others, replaces `forge-std` Solidity code with native cheat code assertions from Foundry, we can restrict certain visibility modifiers in the test suite to `view`.
> ♻️ Restrict Visibility Modifiers in Tests

- .gas-snapshot
- test/internal/CreateX._generateSalt.t.sol
The fuzzing parameter `msgSender` in `testFuzz_ShouldBeAFunctionOfMultipleBlockPropertiesAndTheCaller` must _not_ equal `SELF` (i.e. `address(this)`, the test contract) for the following negative assertion to always hold:
```solidity
vm.startPrank(msgSender);
assertNotEq(originalSalt, createXHarness.exposed_generateSalt(), "1100");
vm.stopPrank();
```
> ♻️ Fix `assume` Condition in `testFuzz_ShouldBeAFunctionOfMultipleBlockPropertiesAndTheCaller`

- README.md
- deployments/deployments.json
This PR removes the OP-Endurance test network, which has been completely shut down (I confirmed with the project team):
> ➖ Remove OP-Endurance Test Network

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Kava main network deployment:
- [Kava](https://kavascan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
as well as the new Polygon Amoy test network deployment, which replaces the old Mumbai test network (closes #100):
- [Polygon Sepolia Testnet (Amoy)](https://www.oklink.com/amoy/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
> Please note that OKLink explorer contract verification [API endpoint](https://www.oklink.com/docs/en/#on-chain-tools-contract-verification-verify-source-code) doesn't allow to remove the metadata hash from the bytecode and thus I can't verify the contract currently.
Eventually, we also add the Mantle and Linea Sepolia test network deployments:
- [Mantle Sepolia Testnet](https://explorer.sepolia.mantle.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d …
> ➕ Add Kava Mainnet and Polygon, Mantle, and Linea Sepolia Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add Metis test and main network (Andromeda) deployments:
- [Metis Andromeda](https://andromeda-explorer.metis.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [Metis Sepolia Testnet](https://sepolia-explorer.metisdevops.link/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://andromeda.metis.io/?owner=1088)
~$ cast keccak $(cast code …
```
> ➕ Add Metis Main and Test Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add Mode Sepolia test network deployment (closes #104):
- [Mode Sepolia Testnet](https://sepolia.explorer.mode.network/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://sepolia.mode.network)
```
> ➕ Add Mode Sepolia Testnet Deployment

- .github/workflows/test-createx.yml
Since the original [`romeovs/lcov-reporter-action`](https://github.com/romeovs/lcov-reporter-action) GitHub action seems unmaintained and is still running on the deprecated `Node.js` version `16`, we upgrade to the fork [`sunsergdev/lcov-reporter-action`](https://github.com/sunsergdev/lcov-reporter-action/tree/v0.3.1-fork) that runs on `Node.js` version `20`. Also, see issue: https://github.com/romeovs/lcov-reporter-action/issues/55.
> 👷 Update `lcov-reporter-action` GitHub Action

- .gitmodules
- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add X Layer test and main network deployments:
- [X Layer Sepolia Testnet](https://www.oklink.com/xlayer-test/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [X Layer](https://www.oklink.com/xlayer/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://testrpc.xlayer.tech)
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url …
```
> ➕ Add X Layer Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Chiliz main network deployment (closes #125):
- [Chiliz](https://chiliscan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://rpc.ankr.com/chiliz)
```
> ➕ Add Chiliz Main Network Deployment

- .github/workflows/checks.yml
- README.md
- interface/package.json
- pnpm-lock.yaml
This PR adds a `README` section for the community-maintained Dune dashboards (currently only one is available). Closes #72. Please note that `awesome_bot` will revert with a 403 for Dune dashboard links and thus I add `https://dune.com` to the whitelist in the CI pipeline.
> 📖 Add Community-Maintained Dune Dashboards

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- interface/src/pages/index.tsx
- package.json
- pnpm-lock.yaml
Add Oasis Sapphire test and main network deployments:
- [Oasis Sapphire Testnet](https://explorer.oasis.io/testnet/sapphire/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [Oasis Sapphire](https://explorer.oasis.io/mainnet/sapphire/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://testnet.sapphire.oasis.io)
~$ cast keccak $(cast code …
```
> ➕ Add Oasis Sapphire Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Plume test network deployment (closes #142):
- [Plume Sepolia Testnet](https://test-explorer.plumenetwork.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://test-rpc.plumenetwork.xyz)
```
> ➕ Add Plume Test Network Deployment

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add Story test network (Odyssey) deployment (closes #156):
- [Story Testnet (Odyssey)](https://odyssey.storyscan.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://odyssey.storyrpc.io)
```
> ➕ Add Story Odyssey Test Network Deployment

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add Plume main network deployment (closes #161):
- [Plume](https://explorer.plumenetwork.xyz/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://rpc.plumenetwork.xyz)
```
> ➕ Add Plume Main Network Deployment

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Berachain test and main network deployments:
- [Berachain Testnet (bArtio)](https://bartio.beratrail.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [Berachain](https://berascan.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://bartio.drpc.org)
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://rpc.berachain.com) …
```
> ➕ Add Berachain Test and Main Network Deployments

- .github/workflows/test-createx.yml
- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add IoTeX/HYCHAIN test and main network deployments (resolves #186, #187, and #188):
- [IoTeX Testnet](https://testnet.iotexscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [IoTeX](https://iotexscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [HYCHAIN Testnet](https://testnet.explorer.hychain.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [HYCHAIN](https://explorer.hychain.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code …
```
> ➕ Add IoTeX/HYCHAIN Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
- test/.solhint-tests.json
Add ZKsync Era test and main network deployments (resolves #73):
- [ZKsync Era Sepolia Testnet](https://sepolia-era.zksync.network/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [ZKsync Era](https://era.zksync.network/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://sepolia.era.zksync.dev)
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed …
```
> ➕ Add ZKsync Era Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Abstract test and main network deployments:
- [Abstract Sepolia Testnet](https://sepolia.abscan.org/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [Abstract](https://abscan.org/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://api.testnet.abs.xyz)
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://api.mainnet.abs.xyz) …
```
> ➕ Add Abstract Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
- pnpm-lock.yaml
Add ApeChain test and main network deployments:
- [ApeChain Sepolia Testnet (Curtis)](https://curtis.apescan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed),
- [ApeChain](https://apescan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://curtis.rpc.caldera.xyz/http)
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url …
```
> ➕ Add ApeChain Test and Main Network Deployments

- README.md
- deployments/deployments.json
- hardhat.config.ts
- package.json
Add Katana main network deployment (resolves #225):
- [Katana](https://explorer.katanarpc.com/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://rpc.katana.network)
```
> ➕ Add Katana Main Network Deployment

- README.md
- deployments/deployments.json
- eslint.config.js
- hardhat.config.ts
- interface/eslint.config.js
- interface/package.json
- package.json
- pnpm-lock.yaml
Add Story main network deployment:
- [Story](https://www.storyscan.io/address/ba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed).
```console
~$ cast keccak $(cast code 0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed --rpc-url https://mainnet.storyrpc.io)
```
> ➕ Add Story Main Network Deployment
